language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t ksvijaynkl/frontend -f Dockerfile.dev .
script:
  - docker run -e CI=true ksvijaynkl/frontend npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "FrontEnd"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-619200712172"
  bucket_path: "FrontEnd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
